### ISSUE TITLE
Encoding breaks codegen/parsing

### ISSUE THREAD

**Issue by gsdatta** [PagerDuty/api-schema#82] opened 2020-08-11 01:11 UTC
The OpenAPI spec isn't parseable by the standard swagger parser due to encoded refs.
For example: `#/paths/~1users~1%7Bid%7D~1notification_subscriptions` which should (most likely) be `#/paths/users/{id}/notification_subscriptions`.

Frequent issues:
- `%7B` -> `{`
- `%7D` -> `}`
- `~1` -> sometimes `/` it seems?

To reproduce: run https://github.com/OpenAPITools/openapi-generator against the JSON spec defined in this repo.

**Comment by bzmw** [comment] 2020-08-11 15:20
Hey @gsdatta , openapi generator has a lot of options to run it with and many of the generators interpret schema definitions differently. Can you please give an example of the command you are running.

We use https://github.com/APIDevTools/swagger-cli to bundle this schema definition which is likely doing this escaping. 

I know the ~1 is a standard in OpenAPI for $ref see: https://swagger.io/docs/specification/using-ref/

I'll investigate the url encoding.

**Comment by bzmw** [comment] 2020-08-11 15:27
After an investigation this seems to be by design. https://github.com/APIDevTools/swagger-parser/issues/31#issuecomment-173292704

As $ref's as url's they are url encoded by swagger-cli.

**Comment by gsdatta** [comment] 2020-08-12 17:47
Oh interesting, thanks for investigating! The command I'm running is

```
openapi-generator generate \
	-i https://raw.githubusercontent.com/PagerDuty/api-schema/master/reference/REST/openapiv3.json \
	-g java \
	-o ./src
```

**Comment by bzmw** [comment] 2020-08-12 19:55
Ah looks like this is a known issue for openapi-generator. https://github.com/OpenAPITools/openapi-generator/issues/5720

I'm going to close this issue, and move it to that thread.

**Closed by bzmw** 2020-08-12 19:55 UTC
